### ISSUE TITLE
Docstring wrong for test_daily_max and test_daily_min

### ISSUE THREAD

**Issue by rowan04** [10Electra/python-intermediate-inflammation#14]
daily max: https://github.com/10Electra/python-intermediate-inflammation/blob/2ab47264354154295f358a67f395cf8b59335fbf/tests/test_models.py#L31
daily min: https://github.com/10Electra/python-intermediate-inflammation/blob/2ab47264354154295f358a67f395cf8b59335fbf/tests/test_models.py#L46

**Comment by Wikyboy** [comment]
Issue still not fixed, please reopen @10Electra
