### ISSUE TITLE
Import outside toplevel

### ISSUE THREAD

**Issue by e-reyno** [10Electra/python-intermediate-inflammation#16]
**Describe the bug**
Pylint C0415. Import outside toplevel on line 17 of tests/test_models.py

**To Reproduce**
1. pylint test of test_models.py
2. line 17, 32, 47, 56

**Expected behavior**
Imports should be at top of file.
Re imported some modules.
**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://github.com/10Electra/python-intermediate-inflammation/blob/2ab47264354154295f358a67f395cf8b59335fbf/tests/test_models.py#L17)

**Desktop (please complete the following information):**
 - Windows 11.

**Comment by 10Electra** [comment]
See #9

**Comment by e-reyno** [comment]
> See #9

Please see the last comment in #9
