### ISSUE TITLE
Unreadable Code: Unused variable

### ISSUE THREAD

**Issue by me623** [10Electra/python-intermediate-inflammation#22]
**Describe the bug**
Unused variable "error_expected" on line 59 of models.py.
Code is very confusing.

**To Reproduce**
Linter test models.py for PEP8 compliancy 

**Expected behavior**
Code should be readable

**Link**
https://github.com/10Electra/python-intermediate-inflammation/blob/main/inflammation/models.py

**Comment by e-reyno** [comment]
Please use pylint in future!

**Comment by 10Electra** [comment]
Can't find this instance - maybe on an older branch.
