### ISSUE TITLE
Re call of import inflammation 

### ISSUE THREAD

**Issue by e-reyno** [10Electra/python-intermediate-inflammation#9]
https://github.com/10Electra/python-intermediate-inflammation/blob/2ab47264354154295f358a67f395cf8b59335fbf/tests/test_models.py#L47

You are importing daily min function twice. Imports should be at top of file for readability.

**Comment by 10Electra** [comment]
I believe that to compartmentalise the testing, the proper way is to do the necessary imports for each test within its own function. So since there are two tests in two separate functions, the required module gets imported twice.

**Comment by e-reyno** [comment]
This is incredibly inefficient. You are reading an entire module in twice. Imagine this module is X amount of lines along and you have to re-read this into memory!

**Comment by Wikyboy** [comment]
Issue still not fixed, please reopen @10Electra
